### ISSUE TITLE
create_audio function should have spectrogram parameter...Right?

### ISSUE THREAD

**Issue by miraodasilva** [DinoMan/Bulletin#3]
In bulletin.py

**Comment by DinoMan** [comment]
Yes it does it takes a spectrogram named parameter which by default is false. Setting it to true should also post the spectrogram when you post.

**Comment by miraodasilva** [comment]
So maybe I am being stupid but this is the code for this function in bulletin.py:

def CreateAudio(self, id, audio, rate=50000):
        self.Posts[id] = Audio(audio, rate)
        return self.Posts[id]

How does this take a parameter named spectrogram? i know the Audio class constructor takes it, but this function does not seem to.

**Comment by DinoMan** [comment]
No you're right I seem to have forgotten to add it to the interface. I will make the changes. While I'm at it I will also try to make the spectrogram heatmap image look a bit nicer since it doesn't look great now (low power frequencies are not shown well).

**Comment by miraodasilva** [comment]
Cool

**Comment by DinoMan** [comment]
Wait I haven't done it just yet :-p

**Comment by miraodasilva** [comment]
Lmao aight. Also you forgot to update the install requirements. I can do it if you wish (and close the issue).

**Comment by DinoMan** [comment]
I've done in on my local version in uni i'll do it and close the issues
